#!/bin/bash

# Slackware build script for uqm_remixes

# Written by B. Watson (urchlay@slackware.uk)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# Upstream's files are unversioned. VERSION here is the version of uqm the
# files are intended for (according to their web site).

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=uqm_remixes
VERSION=${VERSION:-0.8.0}
BUILD=${BUILD:-1}
TAG=${TAG:-rdlnx}
PKGTYPE=${PKGTYPE:-txz}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/rdlnx}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

mkdir -p $PKG/usr/share/uqm/content/addons/

# "sources" are zip files that don't get extracted (game uses them as-is).
for disc in 1 2 3 4-1; do
  install -m0644 -oroot -groot \
    $CWD/uqm-remix-disc$disc.uqm \
    $PKG/usr/share/uqm/content/addons/
done

# There is no documentation, so I include my own README.
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
