#!/bin/bash

<<<<<<<< HEAD:system/qt-sudo/qt-sudo.SlackBuild
# Slackware build script for qt-sudo

# Copyright 2025 Matteo Bernardini <ponce@slackbuilds.org>, Pisa, Italy
========
# Slackware build script for pause-nosignal

# Copyright 2026, Lockywolf
>>>>>>>> origin/current:system/pause-nosignal/pause-nosignal.SlackBuild
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

<<<<<<<< HEAD:system/qt-sudo/qt-sudo.SlackBuild
PRGNAM=qt-sudo
VERSION=${VERSION:-20240524_242342e}
========
PRGNAM=pause-nosignal
VERSION=${VERSION:-1.0}
>>>>>>>> origin/current:system/pause-nosignal/pause-nosignal.SlackBuild
BUILD=${BUILD:-1}
TAG=${TAG:-rdlnx}
PKGTYPE=${PKGTYPE:-txz}

COMMIT=19b8ace26bc77898b222a999f570a51190df0dbb

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/rdlnx}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

<<<<<<<< HEAD:system/qt-sudo/qt-sudo.SlackBuild
if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "aarch64" ]; then
  SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

========
>>>>>>>> origin/current:system/pause-nosignal/pause-nosignal.SlackBuild
set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
<<<<<<<< HEAD:system/qt-sudo/qt-sudo.SlackBuild
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.*z
cd $PRGNAM-$VERSION
========
rm -rf $PRGNAM-$COMMIT
tar xvf $CWD/$PRGNAM-$COMMIT.tar.gz
cd $PRGNAM-$COMMIT
>>>>>>>> origin/current:system/pause-nosignal/pause-nosignal.SlackBuild
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} + -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} +

<<<<<<<< HEAD:system/qt-sudo/qt-sudo.SlackBuild
qmake PREFIX=/usr
make
make install INSTALL_ROOT=$PKG

#rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
========
gcc -O2 -o "$PRGNAM" pause-nosignal.c

mkdir -p "$PKG"/usr/bin
cp "$PRGNAM" "$PKG"/usr/bin
mkdir -p "$PKG"/usr/man/man1/
cp pause-nosignal.1 "$PKG"/usr/man/man1/
>>>>>>>> origin/current:system/pause-nosignal/pause-nosignal.SlackBuild

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
<<<<<<<< HEAD:system/qt-sudo/qt-sudo.SlackBuild
cp -a AUTHORS CHANGELOG LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION
========
cp -a \
  README.org \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
>>>>>>>> origin/current:system/pause-nosignal/pause-nosignal.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
